version: '3.3'
services:
  feb-app:
    build:
      context: ./FurExplicitBot/feb-app
    depends_on:
      - feb-db
    restart: always
    env_file:
      - ./FurExplicitBot/shared.env
    logging:
      driver: "json-file"
      options:
        max-size: "1G"

  feb-autopost:
    build:
      context: ./FurExplicitBot/feb-faautopost
    depends_on:
      - feb-db
    restart: always
    env_file:
      - ./FurExplicitBot/shared.env
    logging:
      driver: "json-file"
      options:
        max-size: "1G"

  feb-db:
    build:
      context: ./FurExplicitBot/feb-db
    restart: always
    env_file:
      - ./FurExplicitBot/shared.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "1G"

# networks:
#   default:
#     external:
#       name: nginx_backend

volumes:
  db_data:

