name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: stardrive

    env:
      TOKEN_DISCORD: ${{ secrets.DISCORD_BOT_TOKEN }}
      TOKEN_UPTIME: ${{secrets.TOKEN_UPTIME}}
      TOKEN_BOTSONDISCORD: ${{secrets.TOKEN_BOTSONDISCORD}}
      TOKEN_DISCORDBOTLIST: ${{secrets.TOKEN_DISCORDBOTLIST}}
      TOKEN_DISCORDS: ${{secrets.TOKEN_DISCORDS}}
      TOKEN_DISCORDBOTS: ${{secrets.TOKEN_DISCORDBOTS}}
      TOKEN_MOTIONDEVELOPMENT: ${{secrets.TOKEN_MOTIONDEVELOPMENT}}
      TOKEN_SAUCENAO: ${{secrets.TOKEN_SAUCENAO}}
      LOGIN_FA_COOKIE_A: ${{secrets.FA_COOKIE_A}}
      LOGIN_FA_COOKIE_B: ${{secrets.FA_COOKIE_B}}
      LOGIN_E621_USER: ${{secrets.E621_LOGIN}}
      TOKEN_E621: ${{secrets.E621_API_KEY}}
      MARIADB_PORT: ${{ secrets.MARIADB_PORT }}
      MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
      MARIADB_PASSWORD_ROOT: ${{ secrets.MARIADB_PASSWORD_ROOT }}

    steps:
      - uses: actions/checkout@v2

      - name: Update 3rd party docker containers
        run: docker compose pull

      - name: Build app
        run: docker compose build

      - name: Spin up containers
        run: docker compose up -d
